### ISSUE TITLE
sometimes return undefined

### ISSUE THREAD

**Issue by safeimuslim** [KyleAMathews/image-exists#1]
let a = imageExists(image, function(exists) {
    if (exists) {
      // console.log("it's alive!");
      return 'true'
    }
    else {
      // console.log("oh well");
      return 'false'
    }
  });

// sometimes udefined
 console.log('a: ', a);

**Comment by jayaryan** [comment]
node_modules/image-exists/index.js:8  var img = new Image();            ^ReferenceError: Image is not defined

**Comment by liliangiraudo5** [comment]
Same issue, anything new?

**Comment by abdulloooh** [comment]
if anyone is here in 2022 above, this package will only work for code written in browser currently as it used `Image` function which is not available in `node`

**Comment by safeimuslim** [comment]
noted
